-- Noteit MVP initial schema
-- Database: MySQL 8.x
-- Key strategy: Snowflake ID stored as BIGINT UNSIGNED
-- Content strategy: article body and media files are stored in Aliyun OSS
-- Database stores only metadata, object references, relations, counters and outbox data

CREATE TABLE IF NOT EXISTS `user_profile` (
    `id` BIGINT UNSIGNED NOT NULL COMMENT 'User ID generated by Snowflake',
    `nickname` VARCHAR(64) NOT NULL COMMENT 'Display name',
    `avatar_url` VARCHAR(512) NULL COMMENT 'Avatar URL',
    `bio` VARCHAR(255) NULL COMMENT 'User bio',
    `follower_count` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Redundant follower count',
    `following_count` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Redundant following count',
    `article_count` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Redundant published article count',
    `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'User status: 1-active',
    `version` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Optimistic lock version',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Creation time',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_nickname` (`nickname`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='User profile table';


CREATE TABLE IF NOT EXISTS `article` (
    `id` BIGINT UNSIGNED NOT NULL COMMENT 'Article ID generated by Snowflake',
    `author_id` BIGINT UNSIGNED NOT NULL COMMENT 'Author user ID',
    `title` VARCHAR(100) NOT NULL COMMENT 'Article title',
    `content_object_key` VARCHAR(512) NOT NULL COMMENT 'Body file OSS object key',
    `content_url` VARCHAR(512) NOT NULL COMMENT 'Body file public URL',
    `content_format` VARCHAR(32) NOT NULL DEFAULT 'MARKDOWN' COMMENT 'Body content format',
    `content_preview` VARCHAR(500) NULL COMMENT 'Feed preview text',
    `cover_object_key` VARCHAR(512) NULL COMMENT 'Cover image OSS object key',
    `cover_url` VARCHAR(512) NULL COMMENT 'Cover image public URL',
    `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Article status: 1-published',
    `like_count` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Redundant like count',
    `favorite_count` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Redundant favorite count',
    `summary_status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0-pending 1-processing 2-succeeded 3-failed',
    `summary_text` VARCHAR(1000) NULL COMMENT 'AI summary text',
    `summary_version` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Summary recompute version',
    `summary_retry_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Summary retry count',
    `summary_last_error` VARCHAR(512) NULL COMMENT 'Last summary generation error',
    `published_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Publish time',
    `version` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Optimistic lock version',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Creation time',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
    PRIMARY KEY (`id`),
    KEY `idx_author_id` (`author_id`),
    KEY `idx_status_published_at` (`status`, `published_at` DESC),
    KEY `idx_author_status_published_at` (`author_id`, `status`, `published_at` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Article metadata table';


CREATE TABLE IF NOT EXISTS `article_media` (
    `id` BIGINT UNSIGNED NOT NULL COMMENT 'Media ID generated by Snowflake',
    `article_id` BIGINT UNSIGNED NOT NULL COMMENT 'Article ID',
    `media_type` VARCHAR(32) NOT NULL COMMENT 'Media type, MVP supports IMAGE',
    `object_key` VARCHAR(512) NOT NULL COMMENT 'OSS object key',
    `media_url` VARCHAR(512) NOT NULL COMMENT 'Public media URL',
    `sort_no` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Sort order',
    `is_cover` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Whether this media is the cover: 0-no 1-yes',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Creation time',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
    PRIMARY KEY (`id`),
    KEY `idx_article_id_sort_no` (`article_id`, `sort_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Article media reference table';


CREATE TABLE IF NOT EXISTS `article_like` (
    `id` BIGINT UNSIGNED NOT NULL COMMENT 'Like relation ID generated by Snowflake',
    `article_id` BIGINT UNSIGNED NOT NULL COMMENT 'Article ID',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT 'User ID',
    `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Relation status: 1-active 0-cancelled',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Creation time',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_article_user` (`article_id`, `user_id`),
    KEY `idx_user_id_created_at` (`user_id`, `created_at` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Article like relation table';


CREATE TABLE IF NOT EXISTS `article_favorite` (
    `id` BIGINT UNSIGNED NOT NULL COMMENT 'Favorite relation ID generated by Snowflake',
    `article_id` BIGINT UNSIGNED NOT NULL COMMENT 'Article ID',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT 'User ID',
    `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Relation status: 1-active 0-cancelled',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Creation time',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_article_user` (`article_id`, `user_id`),
    KEY `idx_user_id_created_at` (`user_id`, `created_at` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Article favorite relation table';


CREATE TABLE IF NOT EXISTS `user_follow` (
    `id` BIGINT UNSIGNED NOT NULL COMMENT 'Follow relation ID generated by Snowflake',
    `follower_id` BIGINT UNSIGNED NOT NULL COMMENT 'Follower user ID',
    `followee_id` BIGINT UNSIGNED NOT NULL COMMENT 'Followee user ID',
    `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Relation status: 1-active 0-cancelled',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Creation time',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_follower_followee` (`follower_id`, `followee_id`),
    KEY `idx_followee_id_created_at` (`followee_id`, `created_at` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='User follow relation table';


CREATE TABLE IF NOT EXISTS `upload_task` (
    `id` BIGINT UNSIGNED NOT NULL COMMENT 'Upload task ID generated by Snowflake',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT 'Uploader user ID',
    `biz_type` VARCHAR(32) NOT NULL COMMENT 'Business type: ARTICLE_CONTENT ARTICLE_IMAGE AVATAR',
    `file_name` VARCHAR(255) NOT NULL COMMENT 'Original file name',
    `content_type` VARCHAR(128) NOT NULL COMMENT 'MIME type',
    `content_length` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'File size in bytes',
    `object_key` VARCHAR(512) NOT NULL COMMENT 'OSS object key',
    `public_url` VARCHAR(512) NULL COMMENT 'Public access URL',
    `status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0-created 1-uploaded 2-confirmed 3-failed 4-expired',
    `etag` VARCHAR(128) NULL COMMENT 'OSS etag',
    `expired_at` DATETIME(3) NOT NULL COMMENT 'Presigned URL expiry time',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Creation time',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
    PRIMARY KEY (`id`),
    KEY `idx_user_id_created_at` (`user_id`, `created_at` DESC),
    KEY `idx_status_expired_at` (`status`, `expired_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Upload task table';


CREATE TABLE IF NOT EXISTS `event_outbox` (
    `id` BIGINT UNSIGNED NOT NULL COMMENT 'Outbox row ID generated by Snowflake',
    `event_id` VARCHAR(64) NOT NULL COMMENT 'Unique event identifier',
    `event_type` VARCHAR(64) NOT NULL COMMENT 'Event type',
    `aggregate_type` VARCHAR(64) NOT NULL COMMENT 'Aggregate type, e.g. ARTICLE or USER',
    `aggregate_id` BIGINT UNSIGNED NOT NULL COMMENT 'Aggregate ID',
    `payload` JSON NOT NULL COMMENT 'Event payload',
    `status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0-new 1-sent 2-failed',
    `retry_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Retry count',
    `next_retry_at` DATETIME(3) NULL COMMENT 'Next retry time',
    `last_error` VARCHAR(512) NULL COMMENT 'Last send error',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Creation time',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_event_id` (`event_id`),
    KEY `idx_status_next_retry_at` (`status`, `next_retry_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Transactional outbox table';
