-- MVP login account table.
-- Plain-text passwords are intentionally temporary for local frontend/backend integration.
-- Replace password_plain_text with password_hash before production use.

CREATE TABLE IF NOT EXISTS `auth_user` (
    `id` BIGINT UNSIGNED NOT NULL COMMENT 'Auth account ID generated by current IdGenerator',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT 'Linked user_profile ID',
    `username` VARCHAR(64) NOT NULL COMMENT 'Login username',
    `password_plain_text` VARCHAR(128) NOT NULL COMMENT 'Temporary MVP plain text password',
    `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Account status: 1-active 0-disabled',
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Creation time',
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Update time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_auth_user_user_id` (`user_id`),
    UNIQUE KEY `uk_auth_user_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MVP auth account table';

INSERT INTO `auth_user` (
    `id`, `user_id`, `username`, `password_plain_text`, `status`
) VALUES
    (501, 101, 'style', '123456', 1),
    (502, 102, 'city', '123456', 1),
    (503, 103, 'notes', '123456', 1)
ON DUPLICATE KEY UPDATE
    `user_id` = VALUES(`user_id`),
    `password_plain_text` = VALUES(`password_plain_text`),
    `status` = VALUES(`status`),
    `updated_at` = CURRENT_TIMESTAMP(3);
